var GAME_LEVELS = [
  ["  v                                                                             ",
   "        xxxxxx                                                                  ",
   "      xxx!!!!x                                                                  ",
   "      x!!!!!!x                                                                  ",
   "       v  !!!x                                                                  ",
   "            v                 oo                                 omo            ",
   "   @                         xxxx                               yyyyy           ",
   "  xx!               xx                                   o                      ",
   "                                    o                   xx                      ",
   "                      x                                        o                ",
   "                      x!x                                     xx                ",
   "                  x   xxx                            xx                         ",
   "                 xx       xxx             xxxxxx                                ",
   "                xxx     o                                   xx                  ",
   "               xxxx           x                   p                             ",
   "              xxxxx     o                               x                       ",
   "             xxxxxx                                                     o       ",
   "        xxxxxxxxxxx     xx   xx   xxxxxx x  x  xxxxxxx     xxxxxxx     xxxxxxxxx",
   "                  x!!!!!x     x!!!x                  x!!!!!x                    ",
   "                  x!!!!!x     x!!!x                  x!!!!!x                    ",
   "                  x!!!!!x     x!!!x                  x!!!!!x                    ",
   "                  xxxxxxx     xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "xxxxxxxxxxxxxx                                                                                                    ",
   "xwwwwwwwwwwwwx                                                                                                    ",
   "                                                                                                                  ",
   " t        t                                                                                                       ",
   "  t xxx t                                                                                                         ",
   "   xx xx                                                                                                          ",
   "     @     wwx      xxx                                                                                           ",
   "w         wwwx       x                                                                                            ",
   "ww       wwwwx       x                                                                           wxxxxxxxxxw      ",
   "wwwx   xwwwwwx       xx                                                                          r                ",
   "wwwx   xwwwwwx       x                                                                                     r      ",
   "wwwx o xwwwwwx      xxx                                                                                           ",
   "wwwx   xwwwwwx     xxxxx                             yyy                                                          ",
   "wwwx   xwwwwwxx                                                                                     oo            ",
   "wwwx   xwwwwwx                              xxxxxxx                                                oooo           ",
   "wwwx   xwwwwwx                                wwwwx                                              xxxxxxxx         ",
   "wwwx   xwwwwwxx  x e o e x                 o  t  tx                                            xx                 ",
   "wwwx o xwwwwwx                           xxx      x                           ob           x       ooo            ",
   "wwwx   xwwwwwxo                     o          t  x                           xx           xxx    xxxxxyyyyyyyy   ",
   "wwwx   xwwwwwxx    xxxxx           xxx            x                         xwwwwwx        xwwx                   ",
   "wwwx   xwwwwwx       x                    xxxx    x                    o xwwwwwwwwwwx      xwwwxx                 ",
   "wwwx   xxxxxxx     mxwx                      x    x  ww                xwwwwwwwwwwwwwwx    xxxxxxxxx              ",
   "wwwx     ooooo     xwwwx              xxx    x    x ww w             xwwwwwwwwwwwwwwwwwwxo            x           ",
   "wwwx     ooooo    xwwwwwx                    x    xwww e            xwwwwwwwwwwwwwwwwwwwwx           xxx          ",
   "wwwxxxxxxxxxxxxxxxwwwwwwwxxxxxwwwwxxxxxxxxxxxxwwwwxwwwwwwxxxxxxxxxxxwwwwwwwwwwwwwwwwwwwwwwxxxxxxxxxxxxxxxxxxxxxxxx"],

   ["                                                     xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa                       ",
    "                                                     x i                                                                    ",
    "                                  oooooooooo       ? x       i                                                              ",
    "                           xxxxxxxxxxxxxxxxxxxxxxx   x   i       i                                                          ",
    "                          xxxxaaaaaaaaaaaaaaaaaaaaxxxx                                                                      ",
    "                         xxxxx          i       i aaaa                                                                      ",
    "  @                     xxxxxx i                                                                                            ",
    "xxxxx                  xxxxxxx     i         i                                                                              ",
    "aaaax                 xxxxxxxx                                                                                              ",
    "    x                xxxxxxxxx             i                                                                                ",
    "  i xx              xxxxxxxxxx         i                                                                                    ",
    "    xx             xxxxxxxxxxx   i                                                                                          ",
    "    xx            xxxxaaaaaaaa                                                                                              ",
    " i  xx           xxxxa    i                                                                                                 ",
    "    xxx         xxxxa             i                                                                                         ",
    "    xxx        xxxxa        i                                                                             x                 ",
    "    xxxxxaaxxxxxxxaa                                                                                      x                 ",
    "   iaaaaaaaaaaaaaaa   i                                                            oo                     x                 ",
    "        i          i                                                              xxxx                    x                 ",
    "             i              i                                                   oxxxxxx                   x                 ",
    "   i                                                                 xx         xxxxxxxx          ooo     x                 ",
    "      i          i                                                  xxxx       xxxxxxxxxx        o s o    x                 ",
    "                                                      o      oooo  xxxxxx oo xxxxxxxxxxxxx      xxxxxxx   x                 ",
    "                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                 ",
    "                                                                                                                            ",
    "                                                                                                                            ",
    "                                                                                                                            ",
    "                                                                                                                            ",
    "                                                                                                                            ",
    "                                                                                                                            "],







       ["                                                                                                                            ",
        "                                                                                                                            ",
        "                                                                                                                            ",
        "                                                                                                                            ",
        "                                                                                                                            ",
        "                                                                                                                            ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo            b                                   ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                m               ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                                ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                b                               ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo                                     m          ",
        "            oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo            ooooooooo                           ",
        "                                                                                                                            ",
        "                                                                                  m                       ooooooooo         ",
        "       ooo                                                                                           b                      ",
        "            <yyyyyyy<yy<<<yyyy<yyyyyyy<yyyyyyyyy<yyyyyyyyyyyyy<y<y<yyyyyyyy<              ooooooooo                         ",
        "             <     <  <   <   <       <         <             < < <<       <                                   s            ",
        "              <   <  <     <  <       <         <             < < < <      <                                ooooooooo       ",
        "               < <  <  ooo  < <       <         <             < < <  <     <      ooooooooo                                 ",
        "   ooo          <   <       < <       <         <             < < <   <    <                 s                              ",
        "                <   <       < <       <         <             < < <    <   <                              ooooooooo         ",
        "     ooo        <   <  ooo  < <       <         <      <      < < <     <  <      s          ooooooooo                      ",
        "                <    <     <   <     <           <    < <    <  < <      < <                                          m     ",
        "                <     <   <     <   <             <  <   <  <   < <       <<                               ooooooooo        ",
        "      @         <      <<<       <<<               <<     <<    < <        <       ooooooooo                                ",
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],



];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
